name: setup
description: Common CI setup

runs:
    using: composite
    steps:
        - name: Set up Rust
          uses: dtolnay/rust-toolchain@stable
          with:
              components: rustfmt, clippy

        - name: Cache Rust artifacts
          uses: Swatinem/rust-cache@v2
          with:
              workspaces: ". -> target"
